#!/bin/bash

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc

KPID=0
rfiddetect=0
RFID_DETECTED=0
SOUND="twang_04.mp3"
dbus-monitor --system | while read line 2> /dev/null
do
      
     #echo "===>"$line     
     # ---------------------
     # BUTTON HANLDER
     # DBUS
     # --------------------- 
     # Long Button Press Detected
     # Start or stop Tag Recording
     # ---------------------          
     echo $line | grep "member=lclick_start"                                          
     if [ $? -eq 0 ]; then                                                     
        KillProcess
        if [ -e "$CNF_DATADIR/Run/rfid.record" ]; then 
            StopTagRecording
        else
            StartTagRecording
	    fi        
     fi
     
     # --------------------- 
     # Single Click  Detected
     # User Defined Action
     # --------------------- 
      echo $line | grep "member=click"
      if [ $? -eq 0 ]; then
##         PlaySound "$CNF_DATADIR/Sounds/${SOUND}" 
	    echo "1" > /usr/openkarotz/Extra/1
      fi
      
      # ---------------------  
      # Double Click
      # User Defined Action
      # ---------------------  
      echo $line | grep "member=dclick"
      if [ $? -eq 0 ]; then
##         PlaySound $CNF_DATADIR/Sounds/${SOUND} 
	    echo "2" > /usr/openkarotz/Extra/2
       fi
       
       # ---------------------  
       # Triple Click
       # PreDefined Action
       # ---------------------  
       echo $line | grep "member=tclick"  
       if [ $? -eq 0 ]; then                                       
         #PlaySound $CNF_DATADIR/Sounds/flush.mp3
         PlaySound $CNF_DATADIR/Sounds/${SOUND}
         ##/sbin/reboot
         if [ "$KPID" == "0" ]; then
          python /usr/openkarotz/Extra/nabemu.py >/dev/null &
          KPID=$!
          ##echo "your pid is $PID"
         else
           kill -9 $KPID
           KPID=0
         fi
       fi                                              
 
      # ---------------------
      # RFID HANDLER
      # DBUS
      # ---------------------
      # Process Tag Action
      # ---------------------
 
      # ---------------------                                 
      # Read TAG ID
      # ---------------------
      if [ $RFID_DETECTED -eq 1 ]; then
          
          RFID_ID=$(awk -F\" '{print $2}' <<< "$line")
          #echo "ID ==>"$RFID_ID"<==" 
          RFID_DETECTED=0
          # nabemu
          # create string
          echo $RFID_ID > /usr/openkarotz/Extra/R
          #wget  '"http://'${h}'/vl/rfid.jsp?sn='${mac}'&v=18673&h=4&t='${RFID_ID}'"'
          ##echo '"http://${h}/vl/rfid.jsp?sn=${mac}&v=18673&h=4&t=${RFID_ID}"'
          PlaySound $CNF_DATADIR/Sounds/ready.mp3 
      fi
      
      # ---------------------      
      # Tag Detected 
      # ---------------------
      echo $line | grep "tag_in"     
      if [ $? -eq 0 ]; then
 	    RFID_DETECTED=1         
      fi
   
 done
                                  
